name: Build & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore packages
        run: npm ci

      - name: Test
        run: |
          npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit
          fail-on-error: true
